# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b147f3671a7182c05354723ab91105a5af7d8a63db1dfd730aedb03098180188e0e24153b461be0e1c272d9dba58a25b76c46110c0c83736e6b72a5197238cb7

test:
  secret_key_base: d972d8d9910d976703cf58d21f13359bc2ea6d1cc32246d4ef8d2a8ceda12b2e01fe78cc91d349b5ed6b63b0ddf2c053c3445c0435e0448275c8730a9b75b208

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
